--- Conversão de unidades
-- tipos 
-- operador ::
-- CAST

-- EXEMPLOS

-- CONVERSAO DE TEXTO EM DATA 
--CORRIJA A QUERY ABAIXO UTILIZANDO O OPERADOR ::
SELECT '2021-10-01'::DATE - '2021-02-01'::DATE


--CONVERSAO DE TEXTO EM NUMERO 
--CORRIJA A QUERY ABAIXO UTILIZANDO O OPERADOR ::
SELECT '100'::NUMERIC - '10'::NUMERIC


--CONVERSAO DE NUMERO EM TEXTO
--CORRIJA A QUERY ABAIXO UTILIZANDO O OPERADOR ::

SELECT REPLACE(112122::TEXT, '1','A')

--CONVERSAO DE TEXTO EM DATA 
--CORRIJA A QUERY ABAIXO UTILIZANDO A FUNCAO "CAST"
SELECT CAST('2021-10-01'AS DATE) - CAST('2021-02-01'AS DATE)

