--MANIPULACAO DE TABELAS
-- CRIACAO DE TAbelas A PATIR DE UMA QUERY 
--CRIACAO DE TABELAS A PARTIR DO ZERO
--DELECAO DE TABELAS

--CRIACAO DE TABELA A PARTIR DE UMA QUERY
--CRIE UMA TABELA CHAMA CUSTOMERS_AGE COM O ID E A IDADE DOS CLIENTES
--CHAME-A DE TEMP_TABLES.CUSTOMERS_AGE

SELECT 
	CUSTOMER_ID,
	(CURRENT_DATE - BIRTH_DATE)/365 AS IDADE_CLIENTE 
	INTO TEMP_TABLES.CUSTOMERS_AGE 
FROM SALES.CUSTOMERS


SELECT *
FROM TEMP_TABLES.CUSTOMERS_AGE


-- CRIACAO DE TABELA A PARTIR DO ZERO
-- CRIE UMA TABELA COM A TRADUCAO DOS STATUS PROFISSIONAIS DOS CLIENTES
--CHAME-A DE TEMP_TABLES.PROFISSOES

SELECT DISTINCT PROFESSIONAL_STATUS
FROM SALES.CUSTOMERS


CREATE TABLE TEMP_TABLES.PROFISSOES(
	PROFESSIONAL_STATUS VARCHAR ,
	STATUS_PROFISSIONAL VARCHAR 	
)


INSERT INTO TEMP_TABLES.PROFISSOES
(PROFESSIONAL_STATUS,STATUS_PROFISSIONAL )
VALUES 
	('freelancer','freelancer'),
	('retired','APOSENTADO' ),
	('clt','CLT')

SELECT * FROM TEMP_TABLES.PROFISSOES



--DELECAO DE TABELAS
--DELETE A TABELA TEMP_TABLES.PROFISSOES 


DROP TABLE TEMP_TABLES.PROFISSOES 
