 -- DISTINCT ------------------------------
 
 --SERVE PARA REMOVER LINHAS DUPLICADAS 
 -- E MOSTRAR APENAS LINHAS DISTINTAS
 
--SEM DISTINCT
SELECT BRAND 
FROM SALES.PRODUCTS
-- COM DISTINCT -- APENAS AS MARCAS 
SELECT DISTINCT BRAND 
FROM SALES.PRODUCTS 
-- MARCAS E ANOS DE MODELO
SELECT DISTINCT BRAND, MODEL_YEAR, PRICE
FROM SALES.PRODUCTS 