-- LIMIT -- SERVE PARA LIMITAR O NUMERO DE LINHAS DA CONSULTA
-- 

-- LISTAR AS 10 PREIMEIRAS LINHAS DA TABELA FUNNEL
SELECT * 
FROM SALES.FUNNEL
LIMIT 10

-- LISTA OS 10 PRODUTOS MAIS CAROS DA TABELA PRODUCTS

SELECT *
FROM SALES.PRODUCTS
ORDER BY PRICE DESC
LIMIT 10 