--Linhas - Inserção, atualização e deleção

-- insercao de linhas
-- insira os status'desempregado(a)'e 'estagiario' na temp_tables.prodissoes
INSERT INTO TEMP_TABLES.PROFISSOES
(PROFESSIONAL_STATUS,STATUS_PROFISSIONAL) 
VALUES 
	('freelancer','freelancer'),
	('retired','APOSENTADO' ),
	('clt','CLT')


SELECT * FROM TEMP_TABLES.PROFISSOES

INSERT INTO TEMP_TABLES.PROFISSOES
(PROFESSIONAL_STATUS, STATUS_PROFISSIONAL)
VALUES
('UNEMPLOYED', 'DESEMPREGADO(A)'),
('TRAINEE', 'ESTAGIARIO(A)')


-- ATUALIZACAO DE LINHAS
--CORRIJA A TRADUCAO DE ESTAGIARIO DE TRINEE PARA INTERN

UPDATE TEMP_TABLES.PROFISSOES
SET PROFESSIONAL_STATUS =  'INTERN'
WHERE STATUS_PROFISSIONAL = 'ESTAGIARIO(A)'

SELECT * FROM TEMP_TABLES.PROFISSOES


--DELECAO DE LINHAS
--DELETE AS LINHAS DOS STATUS 'DESEMPREGADO(A)' E ESTAGIARIO

DELETE FROM TEMP_TABLES.PROFISSOES
WHERE STATUS_PROFISSIONAL = 'DESEMPREGADO(A)' 
OR STATUS_PROFISSIONAL = 'ESTAGIARIO(A)'

SELECT * FROM TEMP_TABLES.PROFISSOES