-- Operadores de comparação
-- comparar TRUE E FALSE UTILIZADO COM "WHERE" PARA FILTRAR LINHAS DE UMA SELEÇAO


-- TIPOS = > < >= <= <> 

-- EXEMPLO 1
-- CRIE UMA COLUNA QUE RETORNE TRUE SEMPRE QUE UM CLIENTE FOR UM PROFISSIONAL CLT
SELECT 
CUSTOMER_ID,
FIRST_NAME,
PROFESSIONAL_STATUS,
(PROFESSIONAL_STATUS = 'clt') as cliente_clt
FROM SALES.CUSTOMERS
