--  Operadores lógicos usado para unir expressoes simples em uma composta 

-- AND OR NOT BETWEEN IN LIKE ILIKE IS NULL

-- EXEMPLO USO DO COMANDO BETWEEN 
-- SELECIONE VEICULOS QUE CUSTAM ENTRE
--100K E 200K NA TABELA PRODUCTS 
-- SEM 
SELECT *
FROM SALES.PRODUCTS 
WHERE PRICE >= 100000 AND PRICE <= 200000
-- COM 
SELECT *
FROM SALES.PRODUCTS 
WHERE PRICE BETWEEN  100000 AND  200000

--EXEMPLO 2 COMANDO NOT 
-- SELECIONE VEICULOS QUE CUSTAM ABAIXO DE 100K OU ACIMA 200K
-- SEM NOT 
SELECT *
FROM SALES.PRODUCTS 
WHERE PRICE < 100000 OR  PRICE > 200000
--COM NOT 
SELECT *
FROM SALES.PRODUCTS 
WHERE PRICE NOT BETWEEN 100000 AND  200000

--EXEMPLO 3 COMANDO IN
-- SELECIONAR PRODUTOS QUE SEJAM DA MARCA HONDA, TPYOTA OU RENAULT
--SEM IN 
SELECT *
FROM SALES.PRODUCTS
WHERE BRAND = 'HONDA' OR BRAND = 'TOYOTA' OR BRAND= 'RENAULT'

-- COM IN
SELECT *
FROM SALES.PRODUCTS
WHERE BRAND  IN ('HONDA','TOYOTA','RENAULT')
--WHERE BRAND   NOT IN ('HONDA','TOYOTA','RENAULT')


-- USO DO COMANDO LIKE(MATCHS IMPERFEITOS)
-- SELECIONE OS PRIMEIROS NOMES DISTINTOS DA TAVELA CUSTOMERS QUE 
-- COMECAL COM AS INICIAIS ANA 

SELECT DISTINCT FIRST_NAME 
FROM SALES.CUSTOMERS
WHERE FIRST_NAME LIKE '%ANA' -- NOMES QUE TERMINAM COM ANA 
-- WHERE FIRST_NAME LIKE 'ANA%' NOMES QUE COMECAM COM ANA


-- USO DO COMANDO ILIKE9IGNORA LETRAS MAIUSCULAS E MINUSCULAS)
-- SELECIONE OS PRIMEIROS NOMES DISTINTOS COM INICIAIS 'ANA'

SELECT DISTINCT FIRST_NAME
FROM SALES.CUSTOMERS
WHERE FIRST_NAME ILIKE 'ana%'


--comando is null

--selecionar apenas as linhas que contem nulo no camp population na tabela
select *
from temp_tables.regions
where population is null

