-- SELECT - SELECIONAR AS COLUNAS , QUANDO SELECIONADA ELAS
--DEVEM SER SEPARADAS POR VIRGULA, SEM CONTER VIRGULA ANTES DO FROM 
--O USO DO * É PARA SELICIONAR TODA A TABELA



-- LISTE OS E-MAILS DOS CLIENTES DA TABELA SALES.CUSTOMERS

SELECT EMAIL 
FROM SALES.CUSTOMERS;

-- SELEÇAO DE MAIS DE UMA COLUNA DE UMA TABELA 
-- LISTE OS EMAIL E NOMES DOS CLIENTES DA TABELA SALES.CUSTOMERS

SELECT EMAIL, FIRST_NAME, LAST_NAME  
FROM SALES.CUSTOMERS 

--SELEÇAO DE TODAS AS COLUNAS DE UMA TABELA 
-- LISTE TODOS AS INFROMACOES DOS CLLENTES DA TABELA SALES.CUSTOMERS

 SELECT * FROM SALES.CUSTOMERS