-- TRATAMENTO DE DATAS

--  INTERVAL
-- DATE_TRUNC
-- EXTRACT 
--DATEDIFF


--SOMA DE DATAS UTILIZANDO INTERVAL
--CALCULE A DATA DE HOJE MIAS 10 UNIDADES(DIAS, SEMANAS,MESES, HORAS)

SELECT CURRENT_DATE + 10
SELECT (CURRENT_DATE + INTERVAL '10 WEEKS') :: DATE
SELECT (CURRENT_DATE + INTERVAL '10 MONTHS') :: DATE
SELECT CURRENT_DATE + INTERVAL '10 HOURS'
SELECT (CURRENT_DATE + INTERVAL '10 YEARS') :: DATE



-- TRUCAGEM DE DATAS UTILIZANDO DATE_TRUNC
--CALCULE QUANTAS VITISAS OCORRERAM POR MES NO SITE DA EMPRENSA

SELECT VISIT_PAGE_DATE, COUNT(*)
FROM SALES.FUNNEL
GROUP BY VISIT_PAGE_DATE
ORDER BY VISIT_PAGE_DATE DESC

SELECT 
	 DATE_TRUNC('MONTH', VISIT_PAGE_DATE):: DATE AS VISIT_PAGE_MONTH,
	 COUNT(*)
FROM SALES.FUNNEL
GROUP BY VISIT_PAGE_MONTH
ORDER BY VISIT_PAGE_MONTH DESC

-- EXTRACAO DE UNIDADES DE UMA DATA UTILIZANDO EXTRACT 
-- CALCULE QUAL É O DIA DA SEMANA QUE MAIS RECEBE VISITAS AO SITE 

SELECT 
	EXTRACT('DOW' FROM VISIT_PAGE_DATE) AS DIA_DA_SEMANA,
	COUNT(*)
FROM SALES.FUNNEL
GROUP BY DIA_DA_SEMANA
ORDER BY DIA_DA_SEMANA 

-- DIFERENCA NTRE DATAS COM OPERADOR DE SUBTRACAO(-)
--CALCULE A DIFERECNA ENTRE HOJE E '2018-06-01', EM DIAS, SEMANAS, MESES E ANOS


SELECT (CURRENT_DATE - '2018-06-01')
SELECT (CURRENT_DATE - '2018-06-01') /7
SELECT (CURRENT_DATE - '2018-06-01') / 30
SELECT (CURRENT_DATE - '2018-06-01') / 365












