-- Tratamento Geral
-- CASE WHEN RESPOSTAS ESPECIFICAS PARA DIFERENTES CONDICOES
--COALESCE() UTILAZADP PARA PREENCHER CAMPOS NULOS COM O PRIMEIRO
-- VALOR NAO NUULO DE UMA SEQUENCIA DE VALORES


--EXEMPLOS

--AGRUPAMENTO DE DADOS COM CASE WHEN
--CALCULE O NUMERO DE CLIENTES QUE GANHAM ABAIXO DE 5K, ENTRE 5K E
--10K, ENRTRE 10K E 15K E ACIMA DE 15K



WITH FAIXA_DE_RENDA AS (
	SELECT 
		INCOME,
		CASE
		WHEN INCOME < 5000 THEN '0-5000'
		WHEN INCOME >= 5000 AND INCOME < 10000 THEN '5000-10000'
		WHEN INCOME >= 10000 AND INCOME < 15000 THEN'10000-15000'
		ELSE '+15000'
		END AS FAIXA_RENDA
	FROM SALES.CUSTOMERS
		)

SELECT FAIXA_RENDA, COUNT(*)
FROM FAIXA_DE_RENDA
GROUP BY FAIXA_RENDA




--tratamento de dados nulos com coalesce
--CRIE UMA COLUNA CHAMADA POPULACAO_AJUSTADA NA TABELA TEMP_TABLES.REGIONS
--E PREENCHA COM OS DADOS DA COLUNA POPULATION, MAS CASO ESSE CAMPO
--ESTIVER NULO, PREENCHA COM A POPULACAO MEDIA(GERAL) DAS CIDADES
-- DO BRASIL 
SELECT * FROM TEMP_TABLES.REGIONS LIMIT 10

--OPCAO 1
SELECT
	*,
	CASE
		WHEN POPULATION IS NOT NULL THEN POPULATION 
		ELSE(SELECT AVG(POPULATION) FROM TEMP_TABLES.REGIONS)
		END AS POPULACAO_AJUSTADA
FROM TEMP_TABLES.REGIONS

WHERE POPULATION IS NULL


--OPCAO 2 
SELECT
	*,
	COALESCE(POPULATION,(SELECT AVG(POPULATION) FROM TEMP_TABLES.REGIONS))
	AS POPULACAO_AJUSTADA
	
FROM TEMP_TABLES.REGIONS
WHERE POPULATION IS NULL



		