-- lower()TODO O TEXTO EM LETRA MINUSCLAS
--upper() EM LETRAS MAIYSCULAS
--trim() ESPACOS DE UM TEXTO
--repleace() SUBSTITUIR STRING POR OUTRA 

-- CORRIJA O PRIMEIRO ELEMENTO DAS QUERIES ABAIXO UTILIZANDO OS COMANDOS
-- DE TRATAMENTO DE TEXTO PARA QUE O SESULTADO SEJA SEMPRE TRUE

SELECT upper('São Paulo') = 'SÃO PAULO'

SELECT lower('São Paulo') = 'são paulo'

SELECT trim('SÃO PAULO   ') = 'SÃO PAULO'

SELECT REPLACE('SAO PAULO', 'SAO', 'SÃO') = 'SÃO PAULO'