-- WHERE ----
--FILTRA AS LINHAS DA TABELA DE ACORDO COM UMA CONDICAO
-- SELECICONAR EMAIL DE CLIENTES QUE MORAM EM SANTA CATARINA 
SELECT EMAIL, STATE
FROM SALES.CUSTOMERS
WHERE STATE = 'SC'

select distinct state
from SALES.CUSTOMERS


-- LISTE OS EMIALS DOS CLIENTES QUE MORAM 
--NO ESTADO DE SC OU MATO GROSSO DO SUL

SELECT EMAIL, STATE
FROM SALES.CUSTOMERS
WHERE STATE = 'SC' OR STATE ='MS'

--LISTE O EMAILS DE CLIENTES QUE MORAM NO ESTADO DE SC
-- OU MATO GROSSO DO SUL QUE TEM MAIS DE 30 ANOS

select distinct BIRTH_DATE
from SALES.CUSTOMERS

SELECT EMAIL, STATE, BIRTH_DATE
FROM SALES.CUSTOMERS
WHERE (STATE = 'SC' OR STATE ='MS') AND BIRTH_DATE < '19911231'